# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MH_cal <- function(theta0, x0, y0, z0, alpha0, err0, ind) {
    .Call(`_MCNR_MH_cal`, theta0, x0, y0, z0, alpha0, err0, ind)
}

MH_update <- function(x0, n) {
    .Call(`_MCNR_MH_update`, x0, n)
}

phi_deriv <- function(phi0, z0, alphaz0) {
    .Call(`_MCNR_phi_deriv`, phi0, z0, alphaz0)
}

theta_deriv <- function(theta0, x0, alphaz0, y0, complete_pos) {
    .Call(`_MCNR_theta_deriv`, theta0, x0, alphaz0, y0, complete_pos)
}

